version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anna-wp
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:php5.6
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

volumes:
  db_data:
